name: Build and Push Image to ACR

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Login to Azure
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.ACR_LOGIN_SERVER }}
                  username: ${{ secrets.ACR_USERNAME }}
                  password: ${{ secrets.ACR_PASSWORD }}
            
            - name: Build and Push Image to ACR
              run: |
                  docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }} .
                  docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }}

            - name: Logout of Azure
              run: az logout