name: Build and Push Image to ACR - PROD

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
  
            - name: Get next version
              uses: reecetech/version-increment@2024.4.3
              id: version
              with:
                scheme: semver
                increment: patch
                release_branch: dev
                
            - name: Create a GitHub Release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.PAT }}
              with:
                tag_name: ${{ steps.version.outputs.version }}
                release_name: ${{ steps.version.outputs.version }}
                body: ${{ steps.version.outputs.version }}

            - name: Login to Azure
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.ACR_LOGIN_SERVER }}
                  username: ${{ secrets.ACR_USERNAME }}
                  password: ${{ secrets.ACR_PASSWORD }}
            
            - name: Build and Push Image to ACR
              run: |
                  docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ steps.version.outputs.version }} .
                  docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ steps.version.outputs.version }}

            - name: Chekcout cicd repository
              uses: actions/checkout@v2
              with:
                repository: 'Suah-Cho/cicd'
                ref: main
                token: ${{ secrets.PAT }}
                path: cicd
            
            - name: Update Image Manifest
              run: |
                sed -i '/frontend:/,/backend:/{s|image: arctestsa.azurecr.io/frontend:.*|image: arctestsa.azurecr.io/frontend:'"${{ steps.version.outputs.version }}"'|}' cicd/resources/docker-compose.yml
                cat cicd/resources/docker-compose.yml
            
            - name: Commit and Push Image Manifest File
              run: |
                cd cicd
                git config user.email "${{ secrets.USEREMAIL }}"
                git config user.name "${{ secrets.USERNAME }}"
                git commit -am "Update frontend image - ${{ steps.version.outputs.version }}"
                git push origin main